import # test modules
  ./accounts/generator/generator,
  ./accounts/accounts,
  ./accounts/public_accounts,
  ./api,
  ./api/contracts,
  ./api/networks,
  ./bip32,
  ./callrpc,
  ./chats,
  ./contacts,
  ./db_smoke,
  ./mailservers,
  ./messages,
  ./migrations,
  ./mnemonic,
  ./multiaccount,
  ./pendingtxs,
  ./permissions,
  ./settings,
  ./stickers,
  ./tokens,
  ./tx_history
  # ./waku_smoke
